### PR TITLE
added features to request version and license informations

### PR DESCRIPTION
**Pull request by bb-Ricardo**
added two new features to last PR:

* request licenses informations of ESXi hosts and vCenter
* request ESXi and vCenter VMWare version

### CODE REVIEW

**Comment by BaldMansMojo** [comment]
Hi,
downloaded your file but I have to merge them manually due to the fact that I've done several changes. But in general: When I reworked the code from op5 I removed all informations not necessary for monitoring and alerting. This is more kind of reporting and I'm quite unsure if I should add it or not. I think it would be better to do via Vcenter (or am I on the "woodway"?

So give me a feedback why I should add it. Maybe there is something useful I haven't thought about. For now I will close this request but I have the code to implement it.

Martin

**Comment by bb-Ricardo** [comment]
Hi,

well it's about if you licensed your environment properly or not.

2 examples:
* you running a ESXi at home and don't have a vcenter, then it would be great to know when the evaluation licenses runs out
* you have a big environment with hundreds of ESXi host and want to make sure they all use the ame licenses or someone forgot to enter the license while setup.

And I wanted to reduce the amount of esxi icinga plugins to use for monitoring.

**Comment by BaldMansMojo** [comment]
Ok - that's an argument. I will implement this evening.

**Comment by BaldMansMojo** [comment]
I will add as much as possible this weekend because I will have a presentation next Monday about monitoring VMware next Monday on Monitoring Workshop here in Munich.

**Comment by bb-Ricardo** [comment]
I will prepare another pull request this afternoon

**Comment by BaldMansMojo** [comment]
About what? Only to know that we won't run in conficts.

Regards
Martin

**Comment by bb-Ricardo** [comment]
This feauture

**Pull request closed without merging**
