### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by simonmeggle**

### CODE REVIEW

**Comment by simonmeggle** [comment]
Fixed bug in host storage adapter whitelisting.

**Comment by BaldMansMojo** [comment]
Hi Simon,
#57. I choosed --statelabels instead of --nostatelabels to avoid confusion with current users. I implemented not in the short version as your last commit because the other way is easier to read than printf "%s%s", $statelabel, $output;

--nostatelabels was not in help. Added --statelabels

Option --plugindirname was nonsense due to my fault. Copied the variable from another plugin where I needed temporary files. In this plugin it was only used for the session files and could be overwirtten by --sessionfiledir :-( . I corrected it and enhenced it with your additions for OMD and the directory test.

All other is done. See comments on issues. Please test it. I have tested it but it's late in the night.

Best regards
Martin

**Comment by sni** [comment]
Thats quite unusual, i would use statelabels by default. Thats what 99% of the plugins do and i'd say this is what people would expect from a plugin.

**Comment by BaldMansMojo** [comment]
Hi Sven,
ok - rewritten. Instead of --statelabels of --nostatelabels  I use now a default in $statelabels_def which is set to y. It can be overwritten with --statelabels=y/n. Folks like me can set set $statelabels_def to n and don't have to struggle with the "unneccessary" string.
So the recommendations of the guidlines are fulfilled by default but can be changed permanently or on a on demand basis. I think this satisfies all.

As an extra little benefit I don't use a simple string comparision in if (is it y or n). I use a regex case insensitive match for the first letter of the string. This avoids typos. So y is equal to "Yeshergottverdammichnochmal".

Regards
Martin

**Comment by sni** [comment]
sounds good, thanks :-)

**Pull request closed without merging**
