### PR TITLE
fix bad OUM

### PR DESCRIPTION
**Pull request by 6uellerBpanda**

### CODE REVIEW

**Comment by BaldMansMojo** [comment]
Am I right? You only changed the unit (s to sec)?

**Comment by 6uellerBpanda** [comment]
no. chaning to sec was just to harmonize it with host_disk_io_info
i changed the perfdata output 'cause it's not valid (https://www.monitoring-plugins.org/doc/guidelines.html#AEN201) and plugins like check_multi will discard it

**Comment by BaldMansMojo** [comment]
OK - this was taken from the original plugin. I think changing s to sec ist ok. But KB is wrong because it's KB per second (which is a rate) and not KB (which is size). No unit should be right and the template should have an appropriate head line.

**Comment by 6uellerBpanda** [comment]
correct. either we give a shit about the dev guidelines and use something like KBps or compensate it via custom pnp template. your call as it is your baby :)

**Comment by Napsty** [comment]
I'd even go one step further and show the Bytes value in the performance data instead of the KB. See my PR #94 on the net usage.

**Pull request merged**
